spring:
  application:
    name: tv-maze-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/tvmaze}

server:
  port: ${SERVER_PORT:8080}

tvmaze:
  api:
    base-url: https://api.tvmaze.com

logging:
  level:
    root: INFO
    com.pinwox.tvmazeapi: DEBUG